from scripts.UI.MainMenuScreen.Submenus.HubMenu import *
from scripts.UI.MainMenuScreen.Submenus.Settings import *
from scripts.UI.MainMenuScreen.Submenus.Credits import *
from scripts.UI.MainMenuScreen.Submenus.NewWorld import *
from scripts.UI.MainMenuScreen.Submenus.LoadWorld import *
from scripts.UI.MainMenuScreen.Submenus.Screenshots import *
from scripts.UI.MainMenuScreen.Submenus.Loading import *
from scripts.UI.MainMenuScreen.Submenus.Error import *
from scripts.UI.MainMenuScreen.Submenus.Addons import *
